import mongoose from "mongoose";
import Location from "../api/models/Location.model.js";

const LOCATIONS = [
    { city: "Kabul", country: "Afghanistan" },
    { city: "Kandahar", country: "Afghanistan" },
    { city: "Tirana", country: "Albania" },
    { city: "Durrës", country: "Albania" },
    { city: "Algiers", country: "Algeria" },
    { city: "Oran", country: "Algeria" },
    { city: "Buenos Aires", country: "Argentina" },
    { city: "Córdoba", country: "Argentina" },
    { city: "Sydney", country: "Australia" },
    { city: "Melbourne", country: "Australia" },
    { city: "Vienna", country: "Austria" },
    { city: "Graz", country: "Austria" },
    { city: "Dhaka", country: "Bangladesh" },
    { city: "Chittagong", country: "Bangladesh" },
    { city: "Brussels", country: "Belgium" },
    { city: "Antwerp", country: "Belgium" },
    { city: "São Paulo", country: "Brazil" },
    { city: "Rio de Janeiro", country: "Brazil" },
    { city: "Sofia", country: "Bulgaria" },
    { city: "Plovdiv", country: "Bulgaria" },
    { city: "Phnom Penh", country: "Cambodia" },
    { city: "Battambang", country: "Cambodia" },
    { city: "Douala", country: "Cameroon" },
    { city: "Yaoundé", country: "Cameroon" },
    { city: "Toronto", country: "Canada" },
    { city: "Montreal", country: "Canada" },
    { city: "Santiago", country: "Chile" },
    { city: "Valparaíso", country: "Chile" },
    { city: "Beijing", country: "China" },
    { city: "Shanghai", country: "China" },
    { city: "Bogotá", country: "Colombia" },
    { city: "Medellín", country: "Colombia" },
    { city: "Kinshasa", country: "Congo (Democratic Republic)" },
    { city: "Lubumbashi", country: "Congo (Democratic Republic)" },
    { city: "Zagreb", country: "Croatia" },
    { city: "Split", country: "Croatia" },
    { city: "Havana", country: "Cuba" },
    { city: "Santiago de Cuba", country: "Cuba" },
    { city: "Prague", country: "Czech Republic" },
    { city: "Brno", country: "Czech Republic" },
    { city: "Cairo", country: "Egypt" },
    { city: "Alexandria", country: "Egypt" },
    { city: "Addis Ababa", country: "Ethiopia" },
    { city: "Dire Dawa", country: "Ethiopia" },
    { city: "Paris", country: "France" },
    { city: "Marseille", country: "France" },
    { city: "Berlin", country: "Germany" },
    { city: "Hamburg", country: "Germany" },
    { city: "Accra", country: "Ghana" },
    { city: "Kumasi", country: "Ghana" },
    { city: "Athens", country: "Greece" },
    { city: "Thessaloniki", country: "Greece" },
    { city: "Guatemala City", country: "Guatemala" },
    { city: "Quetzaltenango", country: "Guatemala" },
    { city: "Conakry", country: "Guinea" },
    { city: "Nzérékoré", country: "Guinea" },
    { city: "Port-au-Prince", country: "Haiti" },
    { city: "Cap-Haïtien", country: "Haiti" },
    { city: "Tegucigalpa", country: "Honduras" },
    { city: "San Pedro Sula", country: "Honduras" },
    { city: "Budapest", country: "Hungary" },
    { city: "Debrecen", country: "Hungary" },
    { city: "Reykjavik", country: "Iceland" },
    { city: "Kopavogur", country: "Iceland" },
    { city: "Mumbai", country: "India" },
    { city: "Delhi", country: "India" },
    { city: "Jakarta", country: "Indonesia" },
    { city: "Surabaya", country: "Indonesia" },
    { city: "Tehran", country: "Iran" },
    { city: "Mashhad", country: "Iran" },
    { city: "Baghdad", country: "Iraq" },
    { city: "Basra", country: "Iraq" },
    { city: "Dublin", country: "Ireland" },
    { city: "Cork", country: "Ireland" },
    { city: "Tel Aviv", country: "Israel" },
    { city: "Jerusalem", country: "Israel" },
    { city: "Rome", country: "Italy" },
    { city: "Milan", country: "Italy" },
    { city: "Tokyo", country: "Japan" },
    { city: "Yokohama", country: "Japan" },
    { city: "Amman", country: "Jordan" },
    { city: "Zarqa", country: "Jordan" },
    { city: "Nairobi", country: "Kenya" },
    { city: "Mombasa", country: "Kenya" },
    { city: "Seoul", country: "South Korea" },
    { city: "Busan", country: "South Korea" },
    { city: "Beirut", country: "Lebanon" },
    { city: "Tripoli", country: "Lebanon" },
    { city: "Tripoli", country: "Libya" },
    { city: "Benghazi", country: "Libya" },
    { city: "Vilnius", country: "Lithuania" },
    { city: "Kaunas", country: "Lithuania" },
    { city: "Kuala Lumpur", country: "Malaysia" },
    { city: "George Town", country: "Malaysia" },
    { city: "Mexico City", country: "Mexico" },
    { city: "Guadalajara", country: "Mexico" },
    { city: "Casablanca", country: "Morocco" },
    { city: "Marrakech", country: "Morocco" },
    { city: "Maputo", country: "Mozambique" },
    { city: "Matola", country: "Mozambique" },
    { city: "Yangon", country: "Myanmar" },
    { city: "Mandalay", country: "Myanmar" },
    { city: "Kathmandu", country: "Nepal" },
    { city: "Pokhara", country: "Nepal" },
    { city: "Amsterdam", country: "Netherlands" },
    { city: "Rotterdam", country: "Netherlands" },
    { city: "Lagos", country: "Nigeria" },
    { city: "Kano", country: "Nigeria" },
    { city: "Oslo", country: "Norway" },
    { city: "Bergen", country: "Norway" },
    { city: "Karachi", country: "Pakistan" },
    { city: "Lahore", country: "Pakistan" },
    { city: "Panama City", country: "Panama" },
    { city: "San Miguelito", country: "Panama" },
    { city: "Lima", country: "Peru" },
    { city: "Arequipa", country: "Peru" },
    { city: "Manila", country: "Philippines" },
    { city: "Davao City", country: "Philippines" },
    { city: "Warsaw", country: "Poland" },
    { city: "Kraków", country: "Poland" },
    { city: "Lisbon", country: "Portugal" },
    { city: "Porto", country: "Portugal" },
    { city: "Doha", country: "Qatar" },
    { city: "Al Rayyan", country: "Qatar" },
    { city: "Moscow", country: "Russia" },
    { city: "Saint Petersburg", country: "Russia" },
    { city: "Riyadh", country: "Saudi Arabia" },
    { city: "Jeddah", country: "Saudi Arabia" },
    { city: "Dakar", country: "Senegal" },
    { city: "Touba", country: "Senegal" },
    { city: "Belgrade", country: "Serbia" },
    { city: "Novi Sad", country: "Serbia" },
    { city: "Singapore", country: "Singapore" },
    { city: "Johannesburg", country: "South Africa" },
    { city: "Cape Town", country: "South Africa" },
    { city: "Madrid", country: "Spain" },
    { city: "Barcelona", country: "Spain" },
    { city: "Colombo", country: "Sri Lanka" },
    { city: "Kandy", country: "Sri Lanka" },
    { city: "Khartoum", country: "Sudan" },
    { city: "Omdurman", country: "Sudan" },
    { city: "Stockholm", country: "Sweden" },
    { city: "Gothenburg", country: "Sweden" },
    { city: "Zurich", country: "Switzerland" },
    { city: "Geneva", country: "Switzerland" },
    { city: "Damascus", country: "Syria" },
    { city: "Aleppo", country: "Syria" },
    { city: "Taipei", country: "Taiwan" },
    { city: "Kaohsiung", country: "Taiwan" },
    { city: "Dar es Salaam", country: "Tanzania" },
    { city: "Mwanza", country: "Tanzania" },
    { city: "Bangkok", country: "Thailand" },
    { city: "Chiang Mai", country: "Thailand" },
    { city: "Tunis", country: "Tunisia" },
    { city: "Sfax", country: "Tunisia" },
    { city: "Ankara", country: "Turkey" },
    { city: "Istanbul", country: "Turkey" },
    { city: "Kyiv", country: "Ukraine" },
    { city: "Kharkiv", country: "Ukraine" },
    { city: "Dubai", country: "United Arab Emirates" },
    { city: "Abu Dhabi", country: "United Arab Emirates" },
    { city: "London", country: "United Kingdom" },
    { city: "Birmingham", country: "United Kingdom" },
    { city: "New York", country: "United States" },
    { city: "Los Angeles", country: "United States" },
    { city: "Montevideo", country: "Uruguay" },
    { city: "Salto", country: "Uruguay" },
    { city: "Caracas", country: "Venezuela" },
    { city: "Maracaibo", country: "Venezuela" },
    { city: "Hanoi", country: "Vietnam" },
    { city: "Ho Chi Minh City", country: "Vietnam" },
    { city: "Lusaka", country: "Zambia" },
    { city: "Kitwe", country: "Zambia" },
    { city: "Harare", country: "Zimbabwe" },
    { city: "Bulawayo", country: "Zimbabwe" },
];

const locationDocuments = LOCATIONS.map((location) => new Location(location));

export const locationSeeds = () => {
  mongoose
    .connect(process.env.DB_URL)
    .then(async () => {
      const allLocation = await Location.find();

      if (allLocation.length) {
        await Location.collection.drop();
      }
    })
    .catch((err) => console.log(`Error deleting data: ${err}`))
    .then(async () => {
        await Location.insertMany(locationDocuments);
        console.log("Collection created successfully!");
    })
    .catch(err => console.log(`Error creating collection: ${err}`))
    .finally(() => mongoose.disconnect())
};
